# Generated by Django 2.2.9 on 2020-02-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200217_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateWriting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_book', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date', to='catalog.DateWriting'),
        ),
    ]
