# Generated by Django 2.2.9 on 2020-02-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200223_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datewriting',
            old_name='date_book',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dates', to='catalog.DateWriting'),
        ),
    ]
