# Generated by Django 2.2.9 on 2020-02-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200223_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datewriting',
            old_name='date',
            new_name='date_book',
        ),
    ]
