# Generated by Django 2.2.9 on 2020-02-24 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200223_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.DateWriting'),
        ),
    ]
