# Generated by Django 2.2.9 on 2020-03-02 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
